//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtTools.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Entities_Trading_Enchantment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entities_Trading_Enchantment() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NbtTools.Resources.Entities.Trading.Enchantment", typeof(Entities_Trading_Enchantment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aqua Affinity.
        /// </summary>
        internal static string minecraft_aqua_affinity {
            get {
                return ResourceManager.GetString("minecraft:aqua_affinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bane of Arthropods.
        /// </summary>
        internal static string minecraft_bane_of_arthropods {
            get {
                return ResourceManager.GetString("minecraft:bane_of_arthropods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Curse of Binding.
        /// </summary>
        internal static string minecraft_binding_curse {
            get {
                return ResourceManager.GetString("minecraft:binding_curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blast Protection.
        /// </summary>
        internal static string minecraft_blast_protection {
            get {
                return ResourceManager.GetString("minecraft:blast_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Channeling.
        /// </summary>
        internal static string minecraft_channeling {
            get {
                return ResourceManager.GetString("minecraft:channeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Depth Strider.
        /// </summary>
        internal static string minecraft_depth_strider {
            get {
                return ResourceManager.GetString("minecraft:depth_strider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Efficiency.
        /// </summary>
        internal static string minecraft_efficiency {
            get {
                return ResourceManager.GetString("minecraft:efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feather Falling.
        /// </summary>
        internal static string minecraft_feather_falling {
            get {
                return ResourceManager.GetString("minecraft:feather_falling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire Aspect.
        /// </summary>
        internal static string minecraft_fire_aspect {
            get {
                return ResourceManager.GetString("minecraft:fire_aspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire Protection.
        /// </summary>
        internal static string minecraft_fire_protection {
            get {
                return ResourceManager.GetString("minecraft:fire_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flame.
        /// </summary>
        internal static string minecraft_flame {
            get {
                return ResourceManager.GetString("minecraft:flame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fortune.
        /// </summary>
        internal static string minecraft_fortune {
            get {
                return ResourceManager.GetString("minecraft:fortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frost Walker.
        /// </summary>
        internal static string minecraft_frost_walker {
            get {
                return ResourceManager.GetString("minecraft:frost_walker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impaling.
        /// </summary>
        internal static string minecraft_impaling {
            get {
                return ResourceManager.GetString("minecraft:impaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infinity.
        /// </summary>
        internal static string minecraft_infinity {
            get {
                return ResourceManager.GetString("minecraft:infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Knockback.
        /// </summary>
        internal static string minecraft_knockback {
            get {
                return ResourceManager.GetString("minecraft:knockback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Looting.
        /// </summary>
        internal static string minecraft_looting {
            get {
                return ResourceManager.GetString("minecraft:looting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loyalty.
        /// </summary>
        internal static string minecraft_loyalty {
            get {
                return ResourceManager.GetString("minecraft:loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Luck of the Sea.
        /// </summary>
        internal static string minecraft_luck_of_the_sea {
            get {
                return ResourceManager.GetString("minecraft:luck_of_the_sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lure.
        /// </summary>
        internal static string minecraft_lure {
            get {
                return ResourceManager.GetString("minecraft:lure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mending.
        /// </summary>
        internal static string minecraft_mending {
            get {
                return ResourceManager.GetString("minecraft:mending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multishot.
        /// </summary>
        internal static string minecraft_multishot {
            get {
                return ResourceManager.GetString("minecraft:multishot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Piercing.
        /// </summary>
        internal static string minecraft_piercing {
            get {
                return ResourceManager.GetString("minecraft:piercing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Power.
        /// </summary>
        internal static string minecraft_power {
            get {
                return ResourceManager.GetString("minecraft:power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projectile Protection.
        /// </summary>
        internal static string minecraft_projectile_protection {
            get {
                return ResourceManager.GetString("minecraft:projectile_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Protection.
        /// </summary>
        internal static string minecraft_protection {
            get {
                return ResourceManager.GetString("minecraft:protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Punch.
        /// </summary>
        internal static string minecraft_punch {
            get {
                return ResourceManager.GetString("minecraft:punch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quick Charge.
        /// </summary>
        internal static string minecraft_quick_charge {
            get {
                return ResourceManager.GetString("minecraft:quick_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Respiration.
        /// </summary>
        internal static string minecraft_respiration {
            get {
                return ResourceManager.GetString("minecraft:respiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Riptide.
        /// </summary>
        internal static string minecraft_riptide {
            get {
                return ResourceManager.GetString("minecraft:riptide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sharpness.
        /// </summary>
        internal static string minecraft_sharpness {
            get {
                return ResourceManager.GetString("minecraft:sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Silk Touch.
        /// </summary>
        internal static string minecraft_silk_touch {
            get {
                return ResourceManager.GetString("minecraft:silk_touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smite.
        /// </summary>
        internal static string minecraft_smite {
            get {
                return ResourceManager.GetString("minecraft:smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soul Speed.
        /// </summary>
        internal static string minecraft_soul_speed {
            get {
                return ResourceManager.GetString("minecraft:soul_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sweeping.
        /// </summary>
        internal static string minecraft_sweeping {
            get {
                return ResourceManager.GetString("minecraft:sweeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swift Sneak.
        /// </summary>
        internal static string minecraft_swift_sneak {
            get {
                return ResourceManager.GetString("minecraft:swift_sneak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thorns.
        /// </summary>
        internal static string minecraft_thorns {
            get {
                return ResourceManager.GetString("minecraft:thorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unbreaking.
        /// </summary>
        internal static string minecraft_unbreaking {
            get {
                return ResourceManager.GetString("minecraft:unbreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Curse of Vanishing.
        /// </summary>
        internal static string minecraft_vanishing_curse {
            get {
                return ResourceManager.GetString("minecraft:vanishing_curse", resourceCulture);
            }
        }
    }
}
