//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtTools.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Entities_Villager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entities_Villager() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NbtTools.Resources.Entities.Villager", typeof(Entities_Villager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Armorer.
        /// </summary>
        internal static string minecraft_armorer {
            get {
                return ResourceManager.GetString("minecraft:armorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Butcher.
        /// </summary>
        internal static string minecraft_butcher {
            get {
                return ResourceManager.GetString("minecraft:butcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cartographer.
        /// </summary>
        internal static string minecraft_cartographer {
            get {
                return ResourceManager.GetString("minecraft:cartographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cleric.
        /// </summary>
        internal static string minecraft_cleric {
            get {
                return ResourceManager.GetString("minecraft:cleric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Farmer.
        /// </summary>
        internal static string minecraft_farmer {
            get {
                return ResourceManager.GetString("minecraft:farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fisherman.
        /// </summary>
        internal static string minecraft_fisherman {
            get {
                return ResourceManager.GetString("minecraft:fisherman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fletcher.
        /// </summary>
        internal static string minecraft_fletcher {
            get {
                return ResourceManager.GetString("minecraft:fletcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leatherworker.
        /// </summary>
        internal static string minecraft_leatherworker {
            get {
                return ResourceManager.GetString("minecraft:leatherworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Librarian.
        /// </summary>
        internal static string minecraft_librarian {
            get {
                return ResourceManager.GetString("minecraft:librarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mason.
        /// </summary>
        internal static string minecraft_mason {
            get {
                return ResourceManager.GetString("minecraft:mason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nitwit.
        /// </summary>
        internal static string minecraft_nitwit {
            get {
                return ResourceManager.GetString("minecraft:nitwit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shepherd.
        /// </summary>
        internal static string minecraft_shepherd {
            get {
                return ResourceManager.GetString("minecraft:shepherd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toolsmith.
        /// </summary>
        internal static string minecraft_toolsmith {
            get {
                return ResourceManager.GetString("minecraft:toolsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weaponsmith.
        /// </summary>
        internal static string minecraft_weaponsmith {
            get {
                return ResourceManager.GetString("minecraft:weaponsmith", resourceCulture);
            }
        }
    }
}
