// <auto-generated />
using System;
using McMerchants.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McMerchants.Migrations
{
    [DbContext(typeof(McMerchantsDbContext))]
    [Migration("20230114165132_AddFactoryTables")]
    partial class AddFactoryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("McMerchants.Models.Database.FactoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FactoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("factory_products", (string)null);
                });

            modelBuilder.Entity("McMerchants.Models.Database.ItemProviderRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Dimension")
                        .HasColumnType("TEXT")
                        .HasColumnName("dimension");

                    b.Property<int>("EndX")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endX");

                    b.Property<int>("EndY")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endY");

                    b.Property<int>("EndZ")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endZ");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("StartX")
                        .HasColumnType("INTEGER")
                        .HasColumnName("startX");

                    b.Property<int>("StartY")
                        .HasColumnType("INTEGER")
                        .HasColumnName("startY");

                    b.Property<int>("StartZ")
                        .HasColumnType("INTEGER")
                        .HasColumnName("startZ");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("item_provider_regions", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("ItemProviderRegion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("McMerchants.Models.Database.FactoryRegion", b =>
                {
                    b.HasBaseType("McMerchants.Models.Database.ItemProviderRegion");

                    b.HasDiscriminator().HasValue("factory");
                });

            modelBuilder.Entity("McMerchants.Models.Database.StorageRegion", b =>
                {
                    b.HasBaseType("McMerchants.Models.Database.ItemProviderRegion");

                    b.HasDiscriminator().HasValue("storage");
                });

            modelBuilder.Entity("McMerchants.Models.Database.TradingRegion", b =>
                {
                    b.HasBaseType("McMerchants.Models.Database.ItemProviderRegion");

                    b.HasDiscriminator().HasValue("trading");
                });

            modelBuilder.Entity("McMerchants.Models.Database.FactoryProduct", b =>
                {
                    b.HasOne("McMerchants.Models.Database.FactoryRegion", "Factory")
                        .WithMany("Products")
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("McMerchants.Models.Database.FactoryRegion", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
