# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dotnet-coverage tool
      run: dotnet tool install -g dotnet-coverage
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Start sonar-scanner for code coverage
      env:
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin /k:"$SONAR_PROJECT_KEY"
        /d:sonar.token="$SONAR_TOKEN"
        /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      
    - name: Test
      run: dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

    - name: Stop sonar-scanner for code coverage
      run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
